[run]
build = "npm run build"

[gptengineer-app]
project_id = "90b468dd-c368-4a17-a57e-585595d8184c"

[[gptengineer-app.openapi]]
url = "https://raw.githubusercontent.com/APIs-guru/openapi-directory/main/APIs/color.pizza/1.0.0/openapi.yaml"
